services:
  # ---------- DB ----------

  certbot:
    profiles: ["prod"]
    image: certbot/certbot:latest
    container_name: certbot
    entrypoint: ""
    command: sh
    volumes:
      - E:/prodvor_data/certbot/www:/var/www/certbot
      - E:/prodvor_data/certbot/letsencrypt:/etc/letsencrypt
    networks: [prodvor-network]