services:

  certbot:
    profiles: ["prod"]
    image: certbot/certbot:latest
    container_name: certbot
    entrypoint: ""
    command: sh
    volumes:
      - /home/user/prodvor_data/certbot/www:/var/www/certbot
      - /home/user/prodvor_data/certbot/letsencrypt:/etc/letsencrypt
    networks: [prodvor-network]
# docker-compose.yml
# Профили:
#   - dev:        фронт с hot-reload, volume (frontend-dev)
#   - prod:       собранный фронт (frontend), без volume, standalone
#   - localstore: локальное S3-хранилище (MinIO) для DEV/теста (можно запускать хоть на прод-сервере)
# Запуск:
#   docker compose --profile dev  up -d frontend-dev backend postgres pgadmin
#   docker compose --profile prod up -d frontend      backend postgres pgadmin nginx
#   docker compose --profile dev  --profile localstore up -d frontend-dev backend postgres pgadmin minio minio-mc
#   docker compose --profile prod --profile localstore up -d frontend backend postgres pgadmin nginx minio minio-mc
# Остановить всё:
#   docker compose down -v

services:
  # ---------- DB ----------
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: prodvor
      POSTGRES_PASSWORD: prodvor
      POSTGRES_DB: prodvor
    ports:
      - "5432:5432"
    volumes:
      - "E:/prodvor_data/postgres/18/docker:/var/lib/postgresql/18/docker"
      - ./postgres/conf/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./postgres/conf/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"
    networks: [prodvor-network]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on: [postgres]
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - type: bind
        source: E:/prodvor_data/pgadmin
        target: /var/lib/pgadmin
    networks: [prodvor-network]

  # ---------- Backend (Flask) ----------
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend
    working_dir: /app
    env_file:
      - ./backend/.env
      - ./backend/.env.local
    environment:
      PORT: 5000
      FLASK_ENV: development
      WATCHDOG_FORCE_POLLING: "true"
      DATABASE_URL: postgresql+psycopg://prodvor:prodvor@postgres:5432/prodvor
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks: [prodvor-network]


  # ---------- Nginx (для prod) ----------
  nginx:
    profiles: ["prod"]
    image: nginx:alpine
    container_name: nginx
    depends_on: [frontend, backend, pgadmin]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - E:/prodvor_data/certbot/www:/var/www/certbot
      - E:/prodvor_data/certbot/letsencrypt:/etc/letsencrypt
    networks: [prodvor-network]

  # ---------- Local S3 Storage (MinIO) ----------
  minio:
    profiles: ["localstore"]
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: localminio
      MINIO_ROOT_PASSWORD: localminio123456
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web-консоль
    volumes:
      - minio-data:/data
    networks: [prodvor-network]

  # одноразовая инициализация bucket + публичное чтение (по желанию)
  minio-mc:
    profiles: ["localstore"]
    image: minio/mc:latest
    container_name: minio-mc
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 localminio localminio123456 &&
      mc mb -p local/media || true &&
      mc anonymous set download local/media || true &&
      tail -f /dev/null
      "
    networks: [prodvor-network]


volumes:
  minio-data:

networks:
  prodvor-network:
    driver: bridge
