services:
  # ---------- DB ----------
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: prodvor
      POSTGRES_PASSWORD: prodvor
      POSTGRES_DB: prodvor
    ports:
      - "5432:5432"
    volumes:
      - "E:/prodvor_data/postgres/18/docker:/var/lib/postgresql/18/docker"
      - ./postgres/conf/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./postgres/conf/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"
    networks: [prodvor-network]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on: [postgres]
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - type: bind
        source: E:/prodvor_data/pgadmin
        target: /var/lib/pgadmin
    networks: [prodvor-network]

  # ---------- Backend (Flask) ----------
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend
    working_dir: /app
    env_file:
      - ./backend/.env
      - ./backend/.env.local
    environment:
      PORT: 5000
      FLASK_ENV: development
      WATCHDOG_FORCE_POLLING: "true"
      DATABASE_URL: postgresql+psycopg://prodvor:prodvor@postgres:5432/prodvor
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks: [prodvor-network]

  # ---------- Frontend PROD ----------
  frontend:
    profiles: ["prod"]
    build:
      context: ./frontend
      dockerfile: ../frontend.Dockerfile
    env_file:
      - ./frontend/.env.production # см. обновлённый prod Dockerfile
    container_name: frontend
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      OTEL_SDK_DISABLED: "1"
      HOST: "0.0.0.0"
      PORT: "3000"
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
    networks: [prodvor-network]

  # ---------- Frontend DEV ----------
  frontend-dev:
    profiles: ["dev"]
    build:
      context: ./frontend
      dockerfile: ../frontend.dev.Dockerfile
    env_file:
      - ./frontend/.env.production #не забыть сменить енв
    container_name: frontend-dev
    working_dir: /app
    environment:
      NEXT_TELEMETRY_DISABLED: "1"
      OTEL_SDK_DISABLED: "1"
      CHOKIDAR_USEPOLLING: "1"
      WATCHPACK_POLLING: "1"
      HOST: "0.0.0.0"
      PORT: "3000"
      NEXT_PUBLIC_API_BASE_URL: "http://backend:5000"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_started
    networks: [prodvor-network]

  # ---------- Nginx (для prod) ----------
  nginx:
    profiles: ["prod"]
    image: nginx:alpine
    container_name: nginx
    depends_on: [frontend, backend, pgadmin]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - E:/prodvor_data/certbot/www:/var/www/certbot
      - E:/prodvor_data/certbot/letsencrypt:/etc/letsencrypt
    networks: [prodvor-network]

  certbot:
    profiles: ["prod"]
    image: certbot/certbot:latest
    container_name: certbot
    entrypoint: ""
    command: sh
    volumes:
      - E:/prodvor_data/certbot/www:/var/www/certbot
      - E:/prodvor_data/certbot/letsencrypt:/etc/letsencrypt
    networks: [prodvor-network]